import React,{useState} from 'react';
const email='bridgepointamericas@gmail.com';
const services=[['Market representation','Your presence in the market. We represent your interests, develop relationships and keep you connected to local opportunities.'],['Market entry strategy','A clear route to market, shaped around your products, priorities and the realities of each country.'],['Distributor & partner development','Identify, assess and engage distributors, agents and commercial partners aligned with your business.'],['Business development','Turn market potential into qualified opportunities, commercial conversations and a focused sales pipeline.'],['Business coordination','Coordinate with local specialists on requirements, business processes and the practical steps of establishing a presence.'],['Ongoing market support','Keep momentum after market entry through partner follow-up, performance reviews and new opportunities.']];
export default function App(){const[menu,setMenu]=useState(false);const[notice,setNotice]=useState('');function contact(e){e.preventDefault();const d=new FormData(e.currentTarget);const body='Name: '+d.get('first')+' '+d.get('last')+'\nCompany: '+d.get('company')+'\nEmail: '+d.get('email')+'\n\n'+d.get('message');window.location.href='mailto:'+email+'?subject='+encodeURIComponent(d.get('subject'))+'&body='+encodeURIComponent(body);setNotice('Your email app will open with your enquiry. Send it there to complete your message. If it does not open, email us directly.');}return <>
<a className="skip" href="#main">Skip to content</a><header><div className="nav wrap"><a className="brand" href="#home" aria-label="BridgePoint Americas home"><img src="/logo-original.png" alt="BridgePoint Americas — Creating opportunities across the Americas"/></a><button className="menu" onClick={()=>setMenu(!menu)} aria-expanded={menu} aria-controls="navigation">{menu?'Close ×':'Menu ☰'}</button><nav id="navigation" className={menu?'open':''} aria-label="Main navigation">{['About','Services','Region','Approach'].map(x=><a key={x} href={'#'+x.toLowerCase()} onClick={()=>setMenu(false)}>{x}</a>)}<a className="button small" href="#contact" onClick={()=>setMenu(false)}>Get in touch <span aria-hidden="true">↗</span></a></nav></div></header>
<main id="main"><section className="hero" id="home"><div className="wrap hero-inner"><p className="eyebrow light">LOCAL INSIGHT. REGIONAL REACH.</p><h1>Your strategic partner<br/>for growth across<br/><em>the Americas.</em></h1><p className="hero-copy">Strategic representation and business development for companies ready to establish and expand their presence across the Caribbean, Central America and South America.</p><a className="button gold" href="#contact">Let's explore your opportunity <span aria-hidden="true">↗</span></a><div className="hero-bottom"><span>BASED IN FLORIDA. CONNECTED TO THE REGION.</span><a href="#services">Discover our services ↓</a></div></div></section>
<section className="proof" aria-label="Our strengths"><div className="wrap proof-grid"><div><strong>40<span>+</span></strong><p>Markets informing our<br/>regional commercial perspective</p></div><div><h2>Trusted relationships</h2><p>Integrity, discretion and a shared commitment to your growth.</p></div><div><h2>Commercial focus</h2><p>Practical priorities that move opportunities towards results.</p></div><div><h2>Regional perspective</h2><p>Local market understanding with a view across borders.</p></div></div></section>
<section className="wrap section" id="services"><div className="section-heading"><div><p className="eyebrow">WHAT WE DO</p><h2>A local partner.<br/>A clearer path forward.</h2></div><p>From the first market assessment to ongoing commercial support, we help connect your ambitions with the right people and opportunities.</p></div><div className="service-grid">{services.map(([t,p],i)=><article key={t}><span className="number">0{i+1}</span><h3>{t}</h3><p>{p}</p></article>)}</div></section>
<section className="about" id="about"><div className="wrap about-grid section"><div><p className="eyebrow">ABOUT THE TEAM</p><h2>Regional experience.<br/><em>Shared commitment.</em></h2></div><div><p className="lead">BridgePoint Americas brings a hands-on approach to helping international companies build their business across the region.</p><p>Our work draws on experience in automotive, mobility and international commercial development, with a regional perspective shaped across Latin America and the Caribbean.</p><p>We work closely with each client to understand their priorities, build the right relationships and stay involved as opportunities move forward. Local insight, clear communication and practical execution guide every engagement.</p><a className="text-link" href="#contact">Start a conversation ↗</a></div></div></section>
<section className="wrap region section" id="region"><div><p className="eyebrow">ONE REGION. MANY MARKET REALITIES.</p><h2>Across borders.<br/>Close to your business.</h2><p>Based in Doral, Florida, we support international companies exploring opportunities across the Caribbean, Central America and South America. Each engagement is shaped around the markets that matter to you.</p></div><div className="region-list">{[['The Caribbean','Connecting companies with diverse island markets.'],['Central America','Building commercial relationships across a connected region.'],['South America','Navigating opportunity in distinct, evolving markets.']].map(([t,p],i)=><div key={t}><span>0{i+1}</span><div><h3>{t}</h3><p>{p}</p></div></div>)}</div></section>
<section className="approach" id="approach"><div className="wrap section"><p className="eyebrow light">HOW WE WORK</p><h2>A focused approach to growth.</h2><div className="steps">{[['Understand','We begin with your objectives, your offer and your priorities.'],['Connect','We assess opportunities and engage relevant commercial partners.'],['Advance','We support follow-through, review progress and refine the next steps.']].map(([t,p],i)=><div key={t}><span>0{i+1}</span><h3>{t}</h3><p>{p}</p></div>)}</div></div></section>
<section className="wrap contact section" id="contact"><div><p className="eyebrow">LET'S TALK</p><h2>Your next market<br/>starts with a<br/><em>conversation.</em></h2><p>Tell us where you want to grow and what you're looking to achieve.</p><a className="email" href={'mailto:'+email}>{email} ↗</a><p className="location">Doral, Florida · United States</p></div><form onSubmit={contact}><div className="fields"><label>First name<input name="first" autoComplete="given-name" required/></label><label>Last name<input name="last" autoComplete="family-name" required/></label><label>Company<input name="company" autoComplete="organization"/></label><label>Email<input name="email" type="email" autoComplete="email" required/></label></div><label>Subject<input name="subject" required/></label><label>How can we help?<textarea name="message" rows="4" required/></label><p className="form-note">This form prepares an email in your email app. Nothing is sent until you choose to send it.</p><button className="button" type="submit">Prepare enquiry ↗</button><p role="status" className="notice">{notice}</p></form></section></main>
<footer><div className="wrap"><span>© {new Date().getFullYear()} BridgePoint Americas</span><span>Creating opportunities across the Americas.</span><a href="#home">Back to top ↑</a></div></footer></>}

